# Generated by Django 5.1.1 on 2024-09-10 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_book_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Product',
        ),
    ]
